baseURL = "/"
languageCode = "en-us"
title = "Show me Finance"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = ""

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Show me Finance"
  description = "A Civic Labs Belgium Project"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "bert@openknowledge.be"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.jpg and overlay.png to set the background.
  backgroundpersection = true

  # hero Section
  [params.hero]
    type = "hero"
    title = "Show Me Finance"
    description = "A [Civic Labs Belgium](//civiclabs.be) project"
    buttontext = "Find out more"

  # about section
  [[params.block]]
    id = "about"
    type = "text"
    title = "What is Show Me Finance?"
    description = "Show me Finance wants to use available data & API's to tell a story about the workings of the Financial sector."
    buttontext = "next"
    # the picture is stored at static/images/
    picture = "pic01.jpg"


  # infos section
  [[params.block]]
    id = "infos"
    type = "text"
    title = "Vulture Funds"
    description = "A vulture fund is a hedge fund, private equity fund or distressed debt fund, that invests in debt considered to be very weak or in default, known as distressed securities."
    # the picture is stored at static/images/
    picture = "pic03.jpg"

#  # custom section
#  [[params.block]]
#    id = "important"
#    # to make custom section copy <theme>/layouts/partials/text.html to /layouts/partials/custom.html and edit it according to your needs.
#    type = "custom"
#    title = "Don't forget"
#    description = "Curabitur massa ante, semper at massa et, semper pellentesque velit. Duis tempor est nisi, a gravida risus malesuada eget. Nunc rutrum arcu laoreet mauris sodales vehicula. Nunc iaculis felis ac dui egestas, vel ullamcorper tellus bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lacinia sem porttitor, fringilla metus at, convallis quam. Integer convallis a justo non pellentesque."
#    # the picture is stored at static/images/
#    picture = "pic04.jpg"

  # contact form
  [[params.block]]
    id = "contact"
    type = "contact"
    title = "Get in Touch"
    picture = "pic05.jpg"

    [params.block.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send message"

  # footer section
  # this section includes last block and social icons

  [params.footer]
    enable = true

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-github"
        link = "https://github.com/CivicLabsBelgium/showmefinance"

      [[params.footer.social]]
        title = "Slack"
        icon = "fa-slack"
        link = "https://civiclabsbelgium.slack.com"

      [[params.footer.social]]
        title = "Meetup"
        icon = "fa-meetup"
        link = "https://www.meetup.com/Civic-Lab-Brussels"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "Â© ShowmeFinance"

      [[params.footer.copyright.notice]]
        text = "Design: [HTML5UP](//html5up.net)"

      [[params.footer.copyright.notice]]
        text = "A [Civic Labs Belgium](https://civiclabs.be/) Project"
